services:
  # Local Mistral service using Ollama
  mistral-local:
    build:
      context: .
      dockerfile: Dockerfile.mistral
    container_name: mistral-local
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  # Web agent service
  web-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-web-agent
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - MISTRAL_MODE=local
      - MISTRAL_LOCAL_ENDPOINT=http://mistral-local:11434
      - MISTRAL_API_ENDPOINT=https://api.mistral.ai/v1/chat/completions
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
    depends_on:
      mistral-local:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  ollama_data:
    driver: local
