---
base: 'http://localhost:3000'
iterations: 100
concurrency: 10
rampup: 30

plan:
  # Health check - lightweight endpoint to warm up
  - name: health_check
    request:
      url: /health
      method: GET
    
  # Create browser session - important core functionality
  - name: create_session
    request:
      url: /browser/session
      method: POST
      headers:
        Content-Type: 'application/json'
      body: '{}'
    assign: session_id_response
    
  # Get session status - using session from previous step
  - name: get_session_status
    request:
      url: '/browser/session/test-session-id'
      method: GET
    
  # Navigate to URL - core browser functionality
  - name: navigate
    request:
      url: /browser/navigate
      method: POST
      headers:
        Content-Type: 'application/json'
      body: |
        {
          "session_id": "test-session-id",
          "url": "https://example.com"
        }
    
  # Browser interaction - click action
  - name: interact_click
    request:
      url: /browser/interact
      method: POST
      headers:
        Content-Type: 'application/json'
      body: |
        {
          "session_id": "test-session-id",
          "action": {
            "Click": {
              "selector": "button"
            }
          }
        }
    
  # Browser interaction - type action
  - name: interact_type
    request:
      url: /browser/interact
      method: POST
      headers:
        Content-Type: 'application/json'
      body: |
        {
          "session_id": "test-session-id",
          "action": {
            "Type": {
              "selector": "input[type='text']",
              "text": "test input"
            }
          }
        }
        
  # Browser interaction - wait action
  - name: interact_wait
    request:
      url: /browser/interact
      method: POST
      headers:
        Content-Type: 'application/json'
      body: |
        {
          "session_id": "test-session-id",
          "action": {
            "Wait": {
              "duration_ms": 1000
            }
          }
        }
    
  # Extract page data
  - name: extract_data
    request:
      url: /browser/extract
      method: POST
      headers:
        Content-Type: 'application/json'
      body: |
        {
          "session_id": "test-session-id",
          "selector": "h1"
        }
    
  # Automation task - AI-powered automation
  - name: automation_task
    request:
      url: /automation/task
      method: POST
      headers:
        Content-Type: 'application/json'
      body: |
        {
          "session_id": "test-session-id",
          "task_description": "Find and click the login button",
          "target_url": "https://example.com"
        }

# Random delays between requests to simulate real user behavior
delay: '1..3'

# Report configuration
reports:
  - name: console
  - name: html
    file: drill-report.html
  - name: json
    file: drill-report.json 